import StyledComponentsRegistry from "@/_styles/registry";
import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import "@/_styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ar">
      <StyledComponentsRegistry>
        <body>
        <Toaster position="top-right" /> {/*NOTE: MUST be placed ABOVE the children directly, not above the body tag*/}
          {children}
          </body>
      </StyledComponentsRegistry>
    </html>
  );
}
